name: Build Aaron's Firmware
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Apply Aaron's mods
        run: bash apply_aaron_mods.sh
      - name: Pull toolchain container
        run: docker pull ghcr.io/synthstromaudible/dbt-toolchain:v$(cat toolchain/REQUIRED_VERSION)
      - name: Build firmware
        run: |
          docker run --rm \
            --user=$(id --user):$(id --group) \
            -e DBT_NO_PYTHON_UPGRADE=1 \
            -v $(pwd):/src \
            ghcr.io/synthstromaudible/dbt-toolchain:v$(cat toolchain/REQUIRED_VERSION) \
            build Release
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: deluge-aaron-firmware
          path: build/Release/*
